#! /bin/bash

../../bin/greedy-qap ../../casos/chr20a.dat
../../bin/greedy-qap ../../casos/chr20c.dat
../../bin/greedy-qap ../../casos/chr22b.dat
../../bin/greedy-qap ../../casos/chr25a.dat
../../bin/greedy-qap ../../casos/esc32a.dat
../../bin/greedy-qap ../../casos/esc64a.dat
../../bin/greedy-qap ../../casos/esc128.dat
../../bin/greedy-qap ../../casos/kra32.dat
../../bin/greedy-qap ../../casos/lipa90a.dat
../../bin/greedy-qap ../../casos/sko42.dat
../../bin/greedy-qap ../../casos/sko49.dat
../../bin/greedy-qap ../../casos/sko81.dat
../../bin/greedy-qap ../../casos/sko90.dat
../../bin/greedy-qap ../../casos/sko100f.dat
../../bin/greedy-qap ../../casos/tai64c.dat
../../bin/greedy-qap ../../casos/tai80a.dat
../../bin/greedy-qap ../../casos/tai100a.dat
../../bin/greedy-qap ../../casos/tai150b.dat
../../bin/greedy-qap ../../casos/tai256c.dat
../../bin/greedy-qap ../../casos/tho150.dat
